language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_moudules

install:
  - yarn install

script:
  - echo 'Hello world'
  - node -v
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in the settings page of your repository, as a secure variable
  keep_history: false
  on:
    branch: dev
